// src/content/nhomZaloTheoCum.ts
// Phụ lục trang Hướng dẫn (M9): danh sách nhóm Zalo hỗ trợ theo cụm. Nguồn: tài liệu "Danh sách nhóm Zalo
// theo cụm hỗ trợ" của HCMUE (tracuu.hcmue.edu.vn/nls-angiang-dsnhomzalo, 2026-10-06). Khác huongDan.ts (dùng
// chung nhiều tỉnh), file này là dữ liệu RIÊNG của khóa đang triển khai — đổi khóa/tỉnh thì thay file này.
// Đây là cụm hỗ trợ qua Zalo, KHÔNG phải danh sách chia lớp.

export interface CumZalo {
  ten: string;
  linkZalo: string;
  donVi: string[];
}

export const nhomZaloTheoCum: { tieuDe: string; luuY: string[]; cum: CumZalo[] } = {
  tieuDe: 'Phụ lục: Nhóm Zalo hỗ trợ theo cụm',
  luuY: [
    'Danh sách đơn vị phân theo cụm chỉ phục vụ hỗ trợ học viên trong quá trình bồi dưỡng, **không phải danh sách chia lớp** chính thức.',
    'Căn cứ **đơn vị công tác** để tham gia đúng nhóm Zalo của cụm mình, không tham gia cùng lúc nhiều nhóm.',
    'Mỗi học viên dùng **1 tài khoản Zalo**, đặt tên tài khoản đúng họ tên của mình.',
  ],
  cum: [
    {
      ten: 'Cụm hỗ trợ 1',
      linkZalo: 'https://zalo.me/g/jiciclxxj0ianu3mfrov',
      donVi: [
        'Trường THPT chuyên Huỳnh Mẫn Đạt',
        'Trường THPT Ngô Sĩ Liên',
        'Trường THPT Nguyễn Hùng Sơn',
        'Trường THPT Nguyễn Trung Trực 1',
        'Trường PT DTNT THCS và THPT An Giang 1',
        'Trường THCS và THPT Mong Thọ',
        'Trường THCS và THPT Võ Văn Kiệt',
        'Trường TH, THCS và THPT Kiên Hải',
        'Trường TH, THCS và THPT Lại Sơn',
        'Trung Tâm GDTX An Giang 1',
        'Trường THCS và THPT An Sơn',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 2',
      linkZalo: 'https://zalo.me/g/187j3jqe6sefqlju6uh5',
      donVi: [
        'Trường THPT Châu Thành',
        'Trường Trung cấp Kỹ thuật - Tổng hợp An Giang',
        'Trường Trung cấp An Giang 1',
        'Trường THPT Hòn Đất',
        'Trường THPT Sóc Sơn',
        'Trường THCS và THPT Bình Sơn',
        'Trường THCS và THPT Nam Thái Sơn',
        'Trường THCS và THPT Nguyễn Hùng Hiệp',
        'Trường THCS và THPT Phan Thị Ràng',
        'Trường THPT Kiên Lương',
        'Trường THPT Thoại Ngọc Hầu',
        'Trường THCS và THPT Ba Hòn',
        'Trung tâm GDNN-GDTX cụm Hà Tiên',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 3',
      linkZalo: 'https://zalo.me/g/makl763buz3ppqibfk7y',
      donVi: [
        'Trung tâm GDNN-GDTX cụm Giồng Riềng',
        'Trường THPT Giồng Riềng',
        'Trường THCS và THPT Bàn Tân Định',
        'Trường THCS và THPT Hòa Hưng',
        'Trường THCS và THPT Hòa Thuận',
        'Trường THCS và THPT Long Thạnh',
        'Trường THCS và THPT Thạnh Lộc',
        'Trường Trung cấp nghề Dân tộc nội trú An Giang',
        'Trường THPT Nguyễn Thần Hiến',
        'Trường THCS và THPT Vĩnh Thắng',
        'Trung tâm GDNN-GDTX cụm Gò Quao',
        'Trường THCS và THPT Thới Quản',
        'Trường THCS và THPT Vĩnh Hòa Hưng Bắc',
        'Trường THPT Gò Quao',
        'Trường THCS và THPT Định An',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 4',
      linkZalo: 'https://zalo.me/g/j3za7zgwqhixlueio59b',
      donVi: [
        'Trường THCS và THPT Tân Thành',
        'Trường THPT Tân Hiệp',
        'Trường THCS và THPT Thạnh Tây',
        'Trường THPT Thạnh Đông',
        'Trường THCS và THPT Vĩnh Thuận',
        'Trường THPT An Minh',
        'Trường THPT Vĩnh Thuận',
        'Trường THCS và THPT U Minh Thượng',
        'Trường THCS và THPT Vĩnh Hòa',
        'Trường THCS và THPT Vĩnh Phong',
        'Trường THCS và THPT Đông Thái',
        'Trường THCS và THPT Minh Thuận',
        'Trường THCS và THPT Nam Yên',
        'Trường THPT An Biên',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 5',
      linkZalo: 'https://zalo.me/g/drb3x1mherfsbj7ldn4v',
      donVi: [
        'Trường THCS và THPT Vân Khánh',
        'Trường THCS và THPT Vĩnh Bình Bắc',
        'Trường THCS và THPT Nguyễn Văn Xiện',
        'Trường THPT An Thới',
        'Trường THPT Dương Đông',
        'Trường THPT Phú Quốc',
        'Trung tâm GDNN-GDTX cụm Đặc khu Phú Quốc',
        'Trường Trung cấp Việt - Hàn Phú Quốc',
        'Trường THPT An Phú',
        'Trường THPT Châu Phong',
        'Trường THPT Châu Phú',
        'Trường THPT Nguyễn Công Trứ',
        'Trường THPT Nguyễn Quang Diêu',
        'Trường THPT Trần Văn Thành',
        'Trường THPT Vĩnh Trạch',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 6',
      linkZalo: 'https://zalo.me/g/5utluxouvzard8ktl5zv',
      donVi: [
        'Trường THPT Vọng Thê',
        'Trường PT DTNT THCS và THPT An Giang 2',
        'Trường THCS và THPT Bình Long',
        'Trường THCS và THPT Long Bình',
        'Trường THCS và THPT Phú Tân',
        'Trung tâm GDNN-GDTX Phú Tân',
        'Trường THPT Bình Mỹ',
        'Trường THPT Nguyễn Hiền',
        'Trường THPT Nguyễn Văn Hưởng',
        'Trường THPT Vĩnh Bình',
        'Trường THPT Võ Thị Sáu',
        'Trường THCS và THPT Vĩnh Hanh',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 7',
      linkZalo: 'https://zalo.me/g/jekclf0jbx5jpawcnpec',
      donVi: [
        'Trung tâm GDNN-GDTX Tịnh Biên',
        'Trường THPT Chuyên Thoại Ngọc Hầu',
        'Trường THPT Nguyễn Trung Trực 2',
        'Trường THPT Nguyễn Văn Thoại',
        'Trường THPT Tân Châu',
        'Trường THPT Vĩnh Xương',
        'Trường THPT Võ Thành Trinh',
        'Trường THCS và THPT Cô Tô',
        'Trung tâm GDTX An Giang 2',
        'Trung tâm GDNN-GDTX Thoại Sơn',
        'Trường THPT Cần Đăng',
        'Trường THPT Chi Lăng',
        'Trường THPT Hòa Lạc',
        'Trường THPT Huỳnh Thị Hưởng',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 8',
      linkZalo: 'https://zalo.me/g/hvwvlnkezun2xbvqj4p8',
      donVi: [
        'Trường THPT Lương Văn Cù',
        'Trường THPT Nguyễn Khuyến',
        'Trường THPT Ung Văn Khiêm',
        'Trường THPT Xuân Tô',
        'Trường THCS và THPT Mỹ Hòa Hưng',
        'Trung tâm GDNN-GDTX An Phú',
        'Trường Trẻ em Khuyết tật An Giang',
        'Trường THPT Bình Thạnh Đông',
        'Trường THPT Châu Thị Tế',
        'Trường THPT Chuyên Thủ Khoa Nghĩa',
        'Trường THPT Nguyễn Bỉnh Khiêm',
        'Trường THPT Nguyễn Chí Thanh',
        'Trường THPT Nguyễn Sinh Sắc',
      ],
    },
    {
      ten: 'Cụm hỗ trợ 9',
      linkZalo: 'https://zalo.me/g/bmrz4c3zhqxqzt1saisu',
      donVi: [
        'Trường THPT Thạnh Mỹ Tây',
        'Trường THPT Tịnh Biên',
        'Trường THCS và THPT Bình Chánh',
        'Trường THCS và THPT Vĩnh Lộc',
        'Trường THPT Ba Chúc',
        'Trường THPT Châu Văn Liêm',
        'Trường THPT Chu Văn An',
        'Trường THPT Long Xuyên',
        'Trường THPT Nguyễn Hữu Cảnh',
        'Trường THPT Quốc Thái',
        'Trung tâm GDNN-GDTX Châu Thành',
        'Trường Trung cấp Kỹ thuật-Công nghệ An Giang',
      ],
    },
  ],
};
